version: '3'

services:


  mahis_release:
    image: nginx:latest
    volumes:
      - ./app/:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf 
    ports:
      - "8001:80"
    networks:
      - mynetwork

networks:
  mynetwork:
    external: true

